server:
  servlet:
    context-path: /lemon
spring:
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/apirunner?characterEncoding=utf-8
    username: root
    password: woshi521	
logging:
  level: 
    root: info
    com.lemon.mapper: trace
  