server:
  port: 8888
  servlet:
    context-path: /
spring:
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/apirunner?characterEncoding=utf-8&useSSL=false
    username: root
    password: woshi521	
logging:
  level: 
    root: info
    com.lemon.mapper: trace
    
  